import { ProfessionList } from '../types/professionList'

export const professionList: ProfessionList[] = [
  { text: 'Backend Engineer', value: 1 },
  { text: 'Frontend Engineer', value: 2 },
  { text: 'Full Stack Engineer', value: 3 },
  { text: 'Web Developer', value: 4 },
  { text: 'Game Developer', value: 5 },
  { text: 'Mobile Developer', value: 6 },
  { text: 'UI/UX Designer', value: 7 },
  { text: 'DevOps Engineer', value: 8 },
  { text: 'Site Reliability Engineer', value: 9 },
  { text: 'Security Engineer', value: 10 },
  { text: 'QA Engineer', value: 11 },
  { text: 'Data Analyst', value: 12 },
  { text: 'Data Scientist', value: 13 },
  { text: 'Data Engineer', value: 14 },
  { text: 'Machine Learning Engineer', value: 15 },
  { text: 'Blockchain Engineer', value: 16 },
  { text: 'Embedded Engineer', value: 17 },
  { text: 'Mainframe Engineer', value: 18 },
  { text: 'Hardware Engineer', value: 19 },
  { text: 'Middleware Engineer', value: 20 },
  { text: 'Firmware Engineer', value: 21 },
  { text: 'Systems Administrator', value: 22 },
  { text: 'Database Administrator', value: 23 },
  { text: 'Network Administrator', value: 24 },
  { text: 'Telecommunications Engineer', value: 25 },
  { text: 'Salesforce Developer', value: 26 },
  { text: 'Business Analyst', value: 27 },
  { text: 'SAP Consultant', value: 28 },
  { text: 'Software Architect', value: 29 },
  { text: 'Scrum Master', value: 30 },
  { text: 'Agile Coach', value: 31 },
  { text: 'Product Manager', value: 32 },
  { text: 'Project Manager', value: 33 },
  { text: 'IT Manager', value: 34 },
  { text: 'IT Director', value: 35 },
  { text: 'Chief Technology Officer (CTO)', value: 36 },
  { text: 'Other', value: 37 },
  { text: 'Solutions Architect', value: 38 },
]
