/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/login": {
    /** @description Login */
    post: operations["AuthController_signIn"];
  };
  "/auth/refresh": {
    /** @description Refresh tokens */
    get: operations["AuthController_refreshToken"];
  };
  "/auth/signup": {
    /** @description Sign Up */
    post: operations["AuthController_signUp"];
  };
  "/user": {
    /** @description Register a new user */
    post: operations["UserController_create"];
  };
  "/user/{id}": {
    /** @description Update a user */
    patch: operations["UserController_update"];
  };
  "/job": {
    get: operations["JobController_list"];
    post: operations["JobController_create"];
  };
  "/job/{id}": {
    get: operations["JobController_getOne"];
  };
  "/job/{id}/apply": {
    post: operations["JobController_apply"];
  };
  "/skillList": {
    get: operations["SkillController_list"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SignInDto: {
      /** @description Email */
      email: string;
      /** @description Pawwrod */
      password: string;
    };
    UserOutputDto: {
      /** @description ID */
      id: string;
      /** @description Email */
      email: string;
    };
    TokenOutputDto: {
      /** @description Access Token */
      accessToken: string;
      /** @description Refresh Token */
      refreshToken: string;
    };
    UserWithTokensOutputDto: {
      /** @description User's info */
      userData: components["schemas"]["UserOutputDto"];
      /** @description Tokens to login */
      tokens: components["schemas"]["TokenOutputDto"];
    };
    SignUpDto: {
      /** @description Name */
      name: string;
      /** @description Email */
      email: string;
      /** @description Password */
      password: string;
    };
    RegisterUserInputDto: {
      /** @description Email */
      email: string;
      /** @description Password */
      password: string;
    };
    UpdateUserInputDto: Record<string, never>;
    LocationDto: {
      city: string;
      country: string;
      province: string;
    };
    SalaryDto: {
      from: number;
      to: number;
      currency: string;
      period: string;
    };
    JobDto: {
      id: string;
      title: string;
      recent: boolean;
      applicants: string[];
      description: string;
      tags: string[];
      locationType: string;
      location: components["schemas"]["LocationDto"];
      salary: components["schemas"]["SalaryDto"];
    };
    RegisterJobInputDto: {
      title: string;
      recent: boolean;
      applicants: string[];
      description: string;
      tags: string[];
      locationType: string;
      location: components["schemas"]["LocationDto"];
      salary: components["schemas"]["SalaryDto"];
    };
    SkillListOutputDto: {
      /** @description Skill List */
      skillList: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** @description Login */
  AuthController_signIn: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserWithTokensOutputDto"];
        };
      };
      /** @description Email is required; Password is required */
      400: {
        content: never;
      };
      /** @description Invalid password */
      401: {
        content: never;
      };
      /** @description User not found */
      404: {
        content: never;
      };
    };
  };
  /** @description Refresh tokens */
  AuthController_refreshToken: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokenOutputDto"];
        };
      };
      /** @description User not authorized */
      401: {
        content: never;
      };
      /** @description User not found */
      404: {
        content: never;
      };
    };
  };
  /** @description Sign Up */
  AuthController_signUp: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignUpDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserWithTokensOutputDto"];
        };
      };
      /** @description Email is required; Password is required; name is required */
      400: {
        content: never;
      };
      /** @description User not authorized */
      401: {
        content: never;
      };
      /** @description User already found */
      404: {
        content: never;
      };
    };
  };
  /** @description Register a new user */
  UserController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterUserInputDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["UserWithTokensOutputDto"];
        };
      };
    };
  };
  /** @description Update a user */
  UserController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserInputDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["UserWithTokensOutputDto"];
        };
      };
    };
  };
  JobController_list: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["JobDto"][];
        };
      };
    };
  };
  JobController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterJobInputDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["JobDto"];
        };
      };
    };
  };
  JobController_getOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["JobDto"];
        };
      };
    };
  };
  JobController_apply: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["JobDto"];
        };
      };
    };
  };
  SkillController_list: {
    responses: {
      default: {
        content: {
          "application/json": components["schemas"]["SkillListOutputDto"];
        };
      };
    };
  };
}
