import { useEffect, useState } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Card from '../components/Card';

export default function Home() {
  const [jobList, setJobList] = useState([]);
  useEffect(() => {
    const fetchData = async () => {
      const data = await fetch('/api/jobs').then(data => data.json());
      const test = await fetch('/api/job/0').then(data => data.json());
      console.log({ test });
      setJobList(data);
    }
    fetchData();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Employ Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Employ Me!</a>
        </h1>

        <div className={styles.grid}>
          {jobList.map(({ description, location, locationType, createdAt, recent, salary, title, tags, id }) => (
            <Card key={id} href={`/job/${id}`}>
              <h2>{title} &rarr;</h2>
              <ul style={{ display: 'flex', justifyContent: 'space-between' }}>
                <li>{location}</li>
                <li>{locationType}</li>
                <li>${salary.from} up to ${salary.to} {salary.currency}/{salary.period}</li>
              </ul>
              <p>
                {description}
              </p>
              <div>
                {tags.map(tag => <span key={tag}>{tag}</span>)}
              </div>
            </Card>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
