import Head from "next/head"
import { useAuthStore } from "stores"
import { ProfileOverview } from "src/components"

export default function Home() {
  const userData = useAuthStore((state: any) => state.user);
  
  return (
    <div>
      <Head>
        <title>Employ Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main><ProfileOverview /></main>
    </div>
  );
}
