import Head from "next/head";
// import styles from "../styles/layout.module.css";

export default function Home() {
  return (
    <div> {/* styles.container */}
      <Head>
        <title>Employ Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Some logic to be implemented to check if user is logged and redirect to /jobs or signin</main>
      <footer> {/* styles.footer */}
        footer
      </footer>
    </div>
  );
}
