import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Card from '../components/Card';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Employ Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Employ Me!</a>
        </h1>

        <div className={styles.grid}>
          <Card href="https://nextjs.org/docs">
            <h2>Software Engineer (Remote only) &rarr;</h2>
            <ul style={{ display: 'flex', justifyContent: 'space-between' }}>
              <li>Vancouver - Canada</li>
              <li>Relocation Only (Sponsored Visa)</li>
              <li>$80,000 up to $100,000 CAD/Annual</li>
            </ul>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
              Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
              when an unknown printer took a galley
            </p>
            <div>
              <span>Javascript 3 yrs</span>
            </div>
          </Card>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
