import { useEffect, useState } from 'react';
import Head from 'next/head';
import styles from '../styles/layout.module.css';
import JobList from '../components/JobList';

export default function Home() {
  
  const [jobList, setJobList] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      const data = await fetch('/api/jobs').then(data => data.json());
      setJobList(data);
    }
    fetchData();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Employ Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Some logic to be implemented to check if user is logged and redirect to /jobs or signin</main>
      <footer className={styles.footer}>
        footer
      </footer>
    </div>
  )
}
