import Head from "next/head";
import { useAuthStore } from "stores";

export default function Home() {
  const userData = useAuthStore((state: any) => state.user);
  
  return (
    <div>
      <Head>
        <title>Employ Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Some logic to be implemented to check if user is logged and redirect to /jobs or signin</main>
      <footer>
        footer
      </footer>
    </div>
  );
}
